#!/usr/bin/env bash
# installs nginx and configures it on a remote server
# Requirements:
#   Install nginx on your web-01 server
#   Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start