#!/usr/bin/env bash
# installs nginx and configures it on a remote server
# Requirements:
#   Install nginx on your web-01 server
#   Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start