#!/usr/bin/env bash
# Installs, configures, and starts the server
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '26i\		rewrite ^/redirect_me https://www.youtube.com/watch?v=bfrP4MEXawA permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start