#!/usr/bin/env bash
# Create a 404 error page
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx restart