#!/usr/bin/env bash
# A Bash script that displays Best School 10 times.
# Using a while loop.

for (( i=0; i<10; i++ )) 
do
  if [ $i -eq 9 ]
    then
      echo "Hi"
    fi
    echo "Best School"
done
